name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: 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
          owner: harveybellini
          base: Exordle
          head: Exordle
